---
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.8

    working_directory: /go/src/github.com/JulienBreux/pody

    environment:
      TEST_RESULTS: /tmp/test-results

    steps:
      - checkout
      - run: mkdir -p $TEST_RESULTS

      - run:
          name: Get deps
          command: go get ./...

      - run:
          name: Run test
          command: go test | tee ${TEST_RESULTS}/go-test.out

      - deploy:
          name: Release
          branch: master
          command: |
            if git log -1 --pretty=%B | grep "^v[0-9]\+\.[0-9]\+\.[0-9]\+$";
            then
              version=$(git log -1 --pretty=%B)
              curl -sL https://git.io/goreleaser | bash
            else
              echo "No release, skipping build"
            fi

      - store_artifacts:
          path: /tmp/test-results
          destination: raw-test-output

      - store_test_results:
          path: /tmp/test-results
